Adicionando endpoint de criação e de update
jairocket/find-your-home pull request #29
Opened 2024-04-30 22:02 UTC by EvertonMutti

https://github.com/jairocket/find-your-home/assets/84800212/c78ca705-cf44-4b32-819f-cd7f3b3b3080

2024-04-30 22:04 UTC, EvertonMutti commented
Observação: Depois de ter feito a pr notei que subi o repositório e o serviço de telephones...t.t, não impacta em nada no fucionamento, só ignore por enquanto.

2024-05-01 01:01 UTC, jairocket requested changes
Fala meu querido!
O validador do cpf/cnpj podemos arrumar depois. Dá pra fazer com uma linha com regex.
mas dá uma olhada nos demais pontos, por favor!

2024-05-01 01:01 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/controllers/CustomerController.java
> +            return ResponseEntity.badRequest().body("Must provide either CPF or CNPJ, and only one of them");
lançar excessão.

- ir na pasta exceptions e criar uma classe CostumerException. 
- Usar o ResourceNotFoundException como modelo
- dentro do if, lançar a excessão 
- throw new CostumerException("Must provide either CPF or CNPJ, and only one of them");
- No ControllerExceptionHandler, criar um exception handler para a CostumerException logo abaixo do já existente
- Usar o que já existe como modelo

2024-05-01 01:01 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/dto/CreateCustomerDTO.java
> +    public void setTelephones(List<CreateTelephoneDTO> telephones) {
porque vc precisou do setter para o telephone?

2024-05-01 01:01 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/dto/UpdateCustomerDTO.java
> +    public boolean equals(Object obj) {
acho que o dto não precisa de hash and equals e do toString. Vc colocou por algum motivo?

2024-05-01 01:01 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
não precisa mudar nesta mr, mas acho que dá pra fazer usando regex

2024-05-01 01:01 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
https://gist.github.com/igorcosta/3a4caa954a99035903ab

2024-05-01 01:01 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
Além disso, acho que fica melhor colocar o método na classe Costumer

2024-05-01 01:07 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/controllers/CustomerController.java
> +            return ResponseEntity.badRequest().body("Must provide either CPF or CNPJ, and only one of them");
Esse if que vc teve que fazer é a prova que vamos precisar usar herança.

2024-05-01 01:24 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/controllers/CustomerController.java
> +            return ResponseEntity.badRequest().body("Must provide either CPF or CNPJ, and only one of them");
Sobre o Regex, discordo pois ela n pega os dois últimos números verificadores do cpf e cnpj.
já sobre excessão, da para fazer uma sem problema nenhum, só n quis envolver mt tempo nisso.

2024-05-01 01:24 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/dto/CreateCustomerDTO.java
> +    public void setTelephones(List<CreateTelephoneDTO> telephones) {
Então, foi gerado automaticamente pelo vsCode mas não utilizo no código.

2024-05-01 01:26 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/dto/UpdateCustomerDTO.java
> +    public boolean equals(Object obj) {
Só segui o padrão colocado no Property e pensei que fosse uma boa prática ter no DTO de update.

2024-05-01 01:28 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
Como dito acima, o regex funciona até certo ponto, mas o cnpj e cpf tem digitos verificadores e é necessário calcular eles para verificar se o cpf/cnpj é confiável, para esse projeto, daria muito certo colocar apenas uma regex, mas procurei por algo mais completo

2024-05-01 01:29 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
a única questão que pega é a qualidade do código, que convenhamos, é tenebrosa.

2024-05-01 01:55 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/dto/UpdateCustomerDTO.java
> +    public boolean equals(Object obj) {
Se tiver hashcode, equals e toString no PropertyDTO, fiz errado. Vou olhar e excluir.
No nosso contexto, faz sentido fazer comparações com a entidade, mas o dto é só um objeto para transferir dados (data transfer object = dto)

2024-05-01 01:57 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/dto/CreateCustomerDTO.java
> +    public void setTelephones(List<CreateTelephoneDTO> telephones) {
se puder apagar pra gente, agradeço imensamente ;)
O dto é só pra transferir dados. Se tivesse usando na lógica, ainda ia

2024-05-01 01:58 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/controllers/CustomerController.java
> +            return ResponseEntity.badRequest().body("Must provide either CPF or CNPJ, and only one of them");
Boa, coloca a excessão lá, por favor. Vai ser bom pra seu portfolio

2024-05-01 02:05 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/controllers/CustomerController.java
> +            return ResponseEntity.badRequest().body("Must provide either CPF or CNPJ, and only one of them");
Sobre a validação do cpf e do cnpj, tinha pensado em validar só o formato mesmo.
O código que vc colocou faz a validação real? Se sim e for essa intenção, blz. Mantemos. Mas acho que vai ser bom refatorar depois para eliminar os comentários e repetição de código.

2024-05-01 02:06 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
com regex fica mais simples haha
Mas não precisa mudar daí agora

2024-05-01 02:08 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
> a única questão que pega é a qualidade do código, que convenhamos, é tenebrosa.

É... confesso que eu não vou querer mostrar no meu github depois do trabalho rs

2024-05-01 02:20 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
Agora entendi haha, se for por isso eu faço regex mesmo, pois refatorar esse código, deus me livre

2024-05-01 02:22 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/controllers/CustomerController.java
> +            return ResponseEntity.badRequest().body("Must provide either CPF or CNPJ, and only one of them");
Sim, faz uma validação real, mas pela qualidade do código, vamos fazer um regex mesmo Xd

2024-05-01 02:22 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
deixa assim por enquanto pra nao te atrasar. depois a gente arruma

2024-05-01 02:35 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/controllers/CustomerController.java
> +            return ResponseEntity.badRequest().body("Must provide either CPF or CNPJ, and only one of them");
Blz. Eu acho massa que vc se preocupou em colocar uma validação real. Mas se eu tivesse fazendo numa empresa, provavelmente, eu ia preferir validar CPF/CNPJ usando a api da receita federal. Que valida e ainda traz nome e data de nascimento da pessoa física. No caso da pessoa jurídica, traz nome da empresa, cnae, etc.
Se fosse gratuita, eu ia sugerir haha

2024-05-01 20:12 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/controllers/CustomerController.java
> +            return ResponseEntity.badRequest().body("Must provide either CPF or CNPJ, and only one of them");
hauhauahuahua, mas mesmo assim me passe essa api meu jovem é bom manter esse tipo de coisa registrado

2024-05-01 20:32 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
Ok, fiz a retirada do validador, e coloquei um match para validar o cpf e cpnj, como não estou encontrando algum pronto rs, vou deixar para depois e deixarei o techo comentado por enquanto

2024-05-01 20:32 UTC, EvertonMutti commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
```
//if (createCustomerDTO.getCpf() != null) {
        //    if (!createCustomerDTO.getCpf().matches(RegexPatterns.cpf)) {
        //        return ResponseEntity.badRequest().body("Invalid CPF");
        //    }
        //} else {
        //    if (!createCustomerDTO.getCnpj().matches(RegexPatterns.cnpj)) {
        //        return ResponseEntity.badRequest().body("Invalid CNPJ");
        //    }
        //}
```

2024-05-01 20:37 UTC, EvertonMutti commented
Ajustado, poderia dar uma olhada novamente?

2024-05-02 00:10 UTC, jairocket commented on src/main/java/com/wyden/findyourhome/utils/validations.java
> +                cpf.equals("11111111111") ||
blz! depois a gente resolve

2024-05-02 00:10 UTC, jairocket approved these changes

2024-05-02 00:42 UTC, merged